### PR TITLE
Pr/validate indicators

### PR DESCRIPTION
**Pull request by phochste**
Providing validation of indicators. 

@jorol Please check the code and the provided Avram schema. In some indicator fields I find a regular expression in the indicators (search "0-9" in the spec) which I don't think is allowed in Avram spec (http://format.gbv.de/schema/avram/specification).

### CODE REVIEW

**Comment by jorol** [comment]
Thanks for PR. I use the schema published by @pkiraly at https://pkiraly.github.io/2018/01/28/marc21-in-json/. If I understand the Avram spec correctly the form of indicator keys is not clearly defined. I would keep it this way and like to ask you to adapt your code to this.

**Comment by phochste** [comment]
@jorol Hmm now I also discover in the schema keys like 'historical-codes' which are not part of the AVRAM spec. What to do about that? Ignore? Include?

**Comment by jorol** [comment]
I would ignore them for the moment. If there are requirements in the future we could discuss this with @pkiraly.

**Comment by pkiraly** [comment]
Hi,

the Avram specification is started as a "common denomimator" of different schemas, and it is a work in progress. We wanted to start with a minimal set. The MARC schema has some more elements which are specific to MARC but not available in PICA (which was the other schema we take into consideration). The MARC standard is itself not very rigorously formatted, so still there are elements, which somewhere available in the standard, but not in the schema I created. Historical elements are most like notes in the standard, and they are not formatted equally everywhere. The meaning of those elements: once they were part of he standard, but now they are not. Sometimes you can find additional information (such as the MARC version and date range). My impression is that catalogs contain records which has such historical elements without being aware of them, so I think this element is useful in validation.

Best,
Péter

**Pull request merged**
